plugins {
    id 'com.android.application'
}
android {
    namespace 'app.recherche.specialiste'
    compileSdk 34
    defaultConfig {
        applicationId 'app.recherche.specialiste'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '1.6.0'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig false
    }
}
